### ISSUE TITLE
"Step 6" missing in the WCA Ansible setup page

### ISSUE THREAD

**Issue by chetan-hireholi** [ibm-cloud-docs/watsonx-code-assistant#2]
Hi team,

For the step "**Add the watsonx Code Assistant Instance to your project**", the "Learn How" hyperlink must point to documentation explaining adding the watsonx code assistant instance to the project. Currently, this information is missing in the main [documentation](https://cloud.ibm.com/docs/watsonx-code-assistant?topic=watsonx-code-assistant-cloud-setup-a#create-project). 

A new "Step 6" would be required to explain how to complete adding the WCA instance.

![image](https://github.com/ibm-cloud-docs/watsonx-code-assistant/assets/19202951/88820b63-ac84-4b0b-9540-a366468b6412)

**Comment by chetan-hireholi** [comment]
fyi @crlordan

**Comment by crlordan** [comment]
Missing instructions were added to the existing section.
