### ISSUE TITLE
404 Page Not found

### ISSUE THREAD

**Issue by cleclerc75** [ibm-cloud-docs/watsonx-code-assistant#3]
When I click on the link
Follow the [instructions from Red Hat](https://docs.redhat.com/en/documentation/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant/2.x_latest/html/red_hat_ansible_lightspeed_with_ibm_watsonx_code_assistant_user_guide/configure-code-assistant_lightspeed-user-guide) to install and configure the Ansible extension for Visual Studio Code and start generating code recommendations.

in the section "Next steps" on this page
https://cloud.ibm.com/docs/watsonx-code-assistant?topic=watsonx-code-assistant-cloud-setup-a

I receive a 404 Page Not Found error

**Comment by crlordan** [comment]
This link has been fixed. The Red Hat team made a lot of changes to their URLs that don't redirect.
